version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExtGitProjectTest1005Project
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
